# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h_pegawai.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(140, 90, 1221, 541))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setRowCount(10000)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 8, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(23)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.buttonPegawaiUtama = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPegawaiUtama.setGeometry(QtCore.QRect(26, 209, 81, 21))
        self.buttonPegawaiUtama.setStyleSheet("")
        self.buttonPegawaiUtama.setObjectName("buttonPegawaiUtama")
        self.buttonSatpamUtama = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSatpamUtama.setGeometry(QtCore.QRect(26, 325, 81, 21))
        self.buttonSatpamUtama.setObjectName("buttonSatpamUtama")
        self.buttonCleanUtama = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCleanUtama.setGeometry(QtCore.QRect(26, 452, 81, 21))
        self.buttonCleanUtama.setObjectName("buttonCleanUtama")
        self.buttonMhsUtama = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMhsUtama.setGeometry(QtCore.QRect(26, 551, 81, 21))
        self.buttonMhsUtama.setObjectName("buttonMhsUtama")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 1361, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("desain ui/h_utama.png"))
        self.label.setObjectName("label")
        self.buttonTentangUtama = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTentangUtama.setGeometry(QtCore.QRect(1260, 30, 75, 23))
        self.buttonTentangUtama.setObjectName("buttonTentangUtama")
        self.buttonMenuUtama = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMenuUtama.setGeometry(QtCore.QRect(1170, 30, 75, 23))
        self.buttonMenuUtama.setObjectName("buttonMenuUtama")
        self.buttonSimpanPegawai = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSimpanPegawai.setGeometry(QtCore.QRect(1233, 660, 101, 26))
        self.buttonSimpanPegawai.setObjectName("buttonSimpanPegawai")
        self.label.raise_()
        self.tableWidget.raise_()
        self.buttonPegawaiUtama.raise_()
        self.buttonSatpamUtama.raise_()
        self.buttonCleanUtama.raise_()
        self.buttonMhsUtama.raise_()
        self.buttonTentangUtama.raise_()
        self.buttonMenuUtama.raise_()
        self.buttonSimpanPegawai.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tanggal"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NPM / NRP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tanggal Lahir"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Usia"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Golongan"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Diagnosa"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Perawatan Gigi"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Pengobatan"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "9 Oktober 2019"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "17081010055"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Kholilul Rachman NM"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "5 April 1998"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "21 "))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "Mahasiswa"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "Alhamdulillah Tidak sakit"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "9 Oktober 2019"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "17081010068"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "Radical Rakhman W"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "15 Mei 1999"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("MainWindow", "Mahasiswa"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("MainWindow", "Alhamdulillah"))
        item = self.tableWidget.item(1, 7)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("MainWindow", "-"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.buttonPegawaiUtama.setText(_translate("MainWindow", "Pegawai"))
        self.buttonSatpamUtama.setText(_translate("MainWindow", "Satpam"))
        self.buttonCleanUtama.setText(_translate("MainWindow", "Clean Service"))
        self.buttonMhsUtama.setText(_translate("MainWindow", "Mahasiswa"))
        self.buttonTentangUtama.setText(_translate("MainWindow", "About"))
        self.buttonMenuUtama.setText(_translate("MainWindow", "Home"))
        self.buttonSimpanPegawai.setText(_translate("MainWindow", "Simpan Perubahan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
